# Generated by Django 5.1.5 on 2025-03-28 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes_admin', '0005_alter_avancemedida_porcentaje'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_aprobador',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_planificador',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_responsable',
        ),
        migrations.AddField(
            model_name='usuario',
            name='organismo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planes_admin.organismosectorial'),
        ),
    ]
