# Generated by Django 5.1.5 on 2025-03-28 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes_admin', '0006_rename_avancemedida_avance_and_more'),
        ('user', '0002_remove_usuario_is_aprobador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='organismo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planes_admin.organismo'),
        ),
    ]
