# Generated by Django 5.1.5 on 2025-03-28 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usuario_organismo'),
        ('user', '0004_crear_roles'),
    ]

    operations = [
    ]
