# Generated by Django 5.1.5 on 2025-04-23 23:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('provincia', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('indicador', models.CharField(max_length=50)),
                ('formula', models.CharField(max_length=200)),
                ('frecuencia', models.CharField(choices=[('cada 5 años', 'Cada 5 años'), ('unica', 'Única'), ('anual', 'Anual')], max_length=50)),
                ('medio_verificacion', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('regulatoria', 'Regulatoria'), ('no regulatoria', 'No regulatoria')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('sigla', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('anio', models.IntegerField()),
                ('resolucion', models.CharField(help_text='Resolucion oficial del PPDA', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'planes',
            },
        ),
        migrations.CreateModel(
            name='PlanComuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes_admin.comuna')),
                ('organismo', models.ForeignKey(help_text='Organismo sectorial responsable de reportar la medida', on_delete=django.db.models.deletion.CASCADE, to='planes_admin.organismo')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes_admin.plan')),
            ],
        ),
        migrations.CreateModel(
            name='PlanMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.IntegerField(blank=True, help_text='Año de ejecución de la medida', null=True, validators=[django.core.validators.MinValueValidator(2020)])),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes_admin.medida')),
                ('organismo', models.ForeignKey(help_text='Organismo sectorial responsable de reportar la medida', on_delete=django.db.models.deletion.CASCADE, to='planes_admin.organismo')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes_admin.plan')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('medio_verificacion', models.CharField(blank=True, max_length=200, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('medida', models.OneToOneField(help_text='Medida', on_delete=django.db.models.deletion.CASCADE, to='planes_admin.planmedida')),
            ],
        ),
    ]
