# Generated by Django 5.1.5 on 2025-01-16 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('provincia', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OrganismoSectorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('sigla', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ano', models.IntegerField()),
                ('resolucion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('indicador', models.CharField(max_length=50)),
                ('formula', models.CharField(max_length=200)),
                ('frecuencia', models.CharField(choices=[('cada 5 años', 'Cada 5 años'), ('unica', 'Única'), ('anual', 'Anual')], max_length=50)),
                ('medio_verificacion', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('regulatoria', 'Regulatoria'), ('no regulatoria', 'No regulatoria')], max_length=50)),
                ('organismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes_admin.organismosectorial')),
            ],
        ),
        migrations.CreateModel(
            name='PlanComuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes_admin.comuna')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes_admin.plan')),
            ],
        ),
        migrations.CreateModel(
            name='PlanMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes_admin.medida')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes_admin.plan')),
            ],
        ),
    ]
