# Generated by Django 5.1.5 on 2025-01-25 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planes_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name_plural': 'planes'},
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='ano',
            new_name='anio',
        ),
    ]
