# Generated by Django 5.1.5 on 2025-03-16 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes_admin', '0002_alter_plan_options_rename_ano_plan_anio'),
    ]

    operations = [
        migrations.AddField(
            model_name='medida',
            name='plan',
            field=models.ForeignKey(default=1, help_text='Plan', on_delete=django.db.models.deletion.CASCADE, to='planes_admin.plan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medida',
            name='organismo',
            field=models.ForeignKey(help_text='Organismo sectorial responsable de reportar la medida', on_delete=django.db.models.deletion.CASCADE, to='planes_admin.organismosectorial'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='resolucion',
            field=models.CharField(help_text='Resolucion oficial del PPDA', max_length=50),
        ),
    ]
