# Generated by Django 5.1.5 on 2025-03-28 02:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes_admin', '0004_avancemedida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avancemedida',
            name='porcentaje',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
