# Generated by Django 5.1.5 on 2025-03-28 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planes_admin', '0005_alter_avancemedida_porcentaje'),
        #('user', '0003_crear_roles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvanceMedida',
            new_name='Avance',
        ),
        migrations.RenameModel(
            old_name='OrganismoSectorial',
            new_name='Organismo',
        ),
    ]
