# Generated by Django 5.1.5 on 2025-03-30 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes_admin', '0006_rename_avancemedida_avance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avance',
            name='medida',
            field=models.OneToOneField(help_text='Medida', on_delete=django.db.models.deletion.CASCADE, to='planes_admin.planmedida'),
        ),
    ]
