# Generated by Django 5.1.5 on 2025-04-02 02:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes_admin', '0007_alter_avance_medida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medida',
            name='organismo',
        ),
        migrations.RemoveField(
            model_name='medida',
            name='plan',
        ),
        migrations.AddField(
            model_name='plancomuna',
            name='organismo',
            field=models.ForeignKey(default=1, help_text='Organismo sectorial responsable de reportar la medida', on_delete=django.db.models.deletion.CASCADE, to='planes_admin.organismo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planmedida',
            name='periodo',
            field=models.IntegerField(blank=True, help_text='Año de ejecución de la medida', null=True, validators=[django.core.validators.MinValueValidator(2020)]),
        ),
        migrations.CreateModel(
            name='ReporteMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('medio_verificacion', models.FileField(upload_to='reportes/')),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('medida', models.OneToOneField(help_text='Medida', on_delete=django.db.models.deletion.CASCADE, to='planes_admin.planmedida')),
            ],
        ),
        migrations.DeleteModel(
            name='Avance',
        ),
    ]
