# Generated by Django 5.1.5 on 2025-04-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes_admin', '0008_remove_medida_organismo_remove_medida_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportemedida',
            name='medio_verificacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
