name: Django CI

on:
  pull_request:
    branches: [john-entrega-continua]
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd PPDApp
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest --disable-warnings -q